# Generated by Django 3.2 on 2021-05-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('F1_main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='color',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
    ]
