# Generated by Django 3.2 on 2021-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F1_main_app', '0003_auto_20210505_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='teams'),
        ),
    ]
