# Generated by Django 3.2 on 2021-05-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F1_main_app', '0004_auto_20210505_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='teams'),
        ),
    ]
