# Generated by Django 3.2 on 2021-05-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F1_main_app', '0005_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='teams/default.jpg', null=True, upload_to='teams'),
        ),
    ]
